# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: m-demo cli  # 构建服务名称

on:
  push:
    branches: [ main ]  #main分支下内容发生改变将会重新构建
    paths:  #当前路径下内容发生变化将会重新构建
    - '.github/workflows/**'
    - '__test__/**'
    - 'src/**'
      
  pull_request:
    branches: [ main ]

jobs: #任务
  build: #build任务

    runs-on: ubuntu-latest  #运行系统

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:  #build任务步骤，每一个“-”都表示一个步骤
    - uses: actions/checkout@v2 #拷贝对应代码都服务器
    - name: Use Node.js ${{ matrix.node-version }}  #步骤名称
      uses: actions/setup-node@v2 #安装node
      with: #传入参数
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  test:

    runs-on: ubuntu-latest
    
    steps:
    - run: touch a.txt
    - run: echo 100 > a.txt
    - run: cat a.txt

    - run: npm ci
